### PR TITLE
Jitpack, Gitignore & Readme

### PR DESCRIPTION
**Pull request by Gustl22**
This pull request includes:
- remove local Eclipse project files
- Jitpack dependency to JUtils, customizable via maven `profiles`
- Improve Readme: Integration guide

Eclipse: Can select profile setting via "Ctrl+Alt+P" to use local **jutils**:
Screenshot from 2019-10-07 00-28-54

### CODE REVIEW

**Comment by twak** [comment]
fantastic, thanks for the idea and code! I have to port this over to my other projects so it will take a little time before I can merge this one. Sorry - start of term here etc...

**Comment by twak** [comment]
Many thanks for the effort; apologies for the delay.

**Comment by twak** [comment]
image

it looks like jitpack doesn't like my lack of a versioning scheme in intelij - does this build for you? If I ask for one of the tags that jitpack invents ("master-f13b77f8a2-11") instead of "master-SNAPSHOT" it works. 

I guess the solution here is start releasing official versions of jutils, siteplan, chordatlas etc...? This is a bit heavy for a project such as this. I'll have a think. 

There are a handful of private projects which rely on this build working - which is why this merge took so long.

**Comment by Gustl22** [comment]
The same warning for me, has something to do with maven and jitpack and IntelliJ in combo, but should load and compile the current snapshot if you [reimport](https://stackoverflow.com/a/16992262/5164462) dependencies via IDE. 
With gradle the problem doesn't exist and is a common way to import volatile packages.
I don't wanted to write down fixed version, as you said it has to be changed every new commit.
It does its job, as packages now can be used and master branch now builds via jitpack, as you can see [here](https://jitpack.io/#twak/campskeleton/master-SNAPSHOT) under builds with new dependencies. The badge may take a while to get updated.

**Comment by twak** [comment]
These projects are at the point where they're transitioning from a single contributor (me) to multiple contributors. I'm going to need more infrastructure around them if I want to encourage contributions. I guess I'll switch to stable + dev branches and periodically (whenever I remember) pull everything onto stable.

Thanks for your efforts tidying up my ancient code.

**Pull request merged**
